### ISSUE TITLE
run_segalign_repeat_masker doesn't appear to work

### ISSUE THREAD

**Issue by glennhickey** [gsneha26/SegAlign#36]
It seems to be duplicating the input file argument?
```
run_segalign_repeat_masker simCow.chr6 --lastz_interval=3000000 --step=3 --ambiguous=iupac,100,100 --nogapped  --markend

Executing: "segalign_repeat_masker /home/hickey/dev/WGA_GPU/simCow.chr6  simCow.chr6 --lastz_interval=3000000 --step=3 --ambiguous=iupac,100,100 --nogapped --markend"

real	0m0.000s
user	0m0.000s
sys	0m0.000s
You must specify a sequence file 
Usage: run_segalign_repeat_masker seq_file [options]
  --seq_file arg        sequence file in FASTA format

```

**Comment by glennhickey** [comment]
If I understand right, the output goes into a randomly-named directory of fragments.  Could you please add the option to specify an output file?  I think that'd make it easier to use (and incorporate into cactus).  thanks!

**Comment by gsneha26** [comment]
So if I understand correctly, do you want all the output segments to be concatenated into the given output file?

**Comment by glennhickey** [comment]
Yes, please!

**Comment by gsneha26** [comment]
run_segalign_repeat_masker bug sorted out and the output file capability added in the latest commit
