### ISSUE TITLE
segalign_repeat_masker runs out of memory on kangaroo rat

### ISSUE THREAD

**Issue by glennhickey** [gsneha26/SegAlign#42]
I'm still having trouble with [kangaroo rat](https://cgl-assemblies.s3.amazonaws.com/dipOrd1.fa).  It was running out of disk before, but fixing that in cactus and giving it 3TB on Terra wasn't enough for it to work. 

Running on a `p3.16large` gives the following, as it presumably runs out of memory (it's at 1 TB of output at that point, but I had another TB free): 

```
Command terminated by signal 9
        Command being timed: "segalign_repeat_masker dipOrd1.fa --lastz_interval=3000000 --markend --neighbor_proportion 0.2 --step=3 --ambiguous=iupac,100,100 --nogapped"
        User time (seconds): 24733.33
        System time (seconds): 7181.33
        Percent of CPU this job got: 749%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:10:57
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 499902360
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 6278
        Minor (reclaiming a frame) page faults: 743073453
        Voluntary context switches: 4601999
        Involuntary context switches: 401723
        Swaps: 0
        File system inputs: 872856
        File system outputs: 2140512800
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
This is the same genome as referred to in #37.

**Comment by gsneha26** [comment]
Solved the error in the latest commit to master. Kangaroo rat repeat-masking ran successfully on p3.16xlarge in less than 30 minutes. Please note the following changes:

1. There is no `--nogapped` option anymore (command in cactus would need to be changed accordingly)
2. There is no wrapper bash script for repeat-masker, so it is `segalign_repeat_masker genome.fa [options]`
3. `cactus_covered_intervals` functionality has been added, just need to specify the corresponding `--M` option.

           -  It has helped with reducing RAM utilization.
           - In the case of kangaroo rat, when the number of output segments was high resulting in a high file output latency, which in turn, caused low GPU utilization. It has now been solved.

**Comment by glennhickey** [comment]
And I guess the output intervals have also changed from one-based to zero-based as well?  
```
File "/usr/local/bin/cactus_fasta_softmask_intervals.py", line 101, in main
"bad line (line %s): %s" % (lineNumber,line)
AssertionError: bad line (line 1): chr1 0 470
```
