### ISSUE TITLE
FAILURE: extra segments in file

### ISSUE THREAD

**Issue by glennhickey** [gsneha26/SegAlign#47]
Does this mean anything to you?  I'm getting this on Terra with the latest Segalign.  This is on a job that seems to have worked an older version:

```
FAILURE: extra segments in file (tmp9.block7.r4845374754.plus.segments: line 94, id=2|chrUn_JH373295|0/id=2|chr27|0+)
(for this usage segments must appear in the same order as the query file, with
all + strand segments before all - strand segments for each query)
FAILURE: extra segments in file (tmp9.block7.r570655384.plus.segments: line 277, id=0|chrB1|0/id=2|chr27|0+)
(for this usage segments must appear in the same order as the query file, with
all + strand segments before all - strand segments for each query)
Command exited with non-zero status 6
Command being timed: "run_segalign /mnt/hdd/node-9c3117ca-a2f4-418b-9a69-1b9eddc9b16c-577754ab-8162-4c0c-89c8-eb40417d150f/tmp6cjn70hu/e132e508-98b8-45ea-99dc-fde827b00bbc/tmpjey6y6io.tmp /mnt/hdd/node-9c3117ca-a2f4-418b-9a69-1b9eddc9b16c-577754ab-8162-4c0c-89c8-eb40417d150f/tmp6cjn70hu/e132e508-98b8-45ea-99dc-fde827b00bbc/tmpjey6y6io.tmp --format=cigar --notrivial --step=2 --ambiguous=iupac,100,100 --ydrop=3000"
```

**Comment by rsharris** [comment]
In lastz, if the --segments option is used, and the input sequences are NOT accessible in random order, the items in the segments file must be consistent with the order in which they 'will be needed'. For most users, "accessible in random order" means YES for twoBit, NO for fasta.

For fasta this should just mean segment names are in the same order as in the fasta file, and all + segments for a given sequence appear before all - segments.

There's some detail here (starting with the paragraph that begins with "Query sequence names must appear in the same order as ..."):
http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.03.html#fmt_segments

That implementation choice seemed more important 15 yrs ago that it does now. Now it would make more sense to read all the segments into memory, sort them by sequence name (to facilitate binary search), and use the appropriate segments as each new fasta sequence arrives.

**Comment by gsneha26** [comment]
@glennhickey the error is definitely in one of the lastz jobs that Bob has pointed out. Ideally, SegAlign divides and sorts the segments in a way to take care of this requirement. I can look into it. Could you share the input files?

**Comment by glennhickey** [comment]
I can confirm that this error doesn't happen with this older commit https://github.com/ComparativeGenomicsToolkit/SegAlign/commit/1d2d38cd38dc398381bc0b4c50edd44eccf5a419

To reproduce:
* [install cactus binaries](https://github.com/ComparativeGenomicsToolkit/cactus/releases)
* make a `config.xml` [as described here](https://github.com/ComparativeGenomicsToolkit/cactus#gpu-acceleration) (I've been meaning to add a command line but haven't gotten around to it yet) 
* copy and unzip the input files from `/public/home/hickey/dev/work/gpu-lastz` on courtyard
* make sure segalign's in your path
* run `cactus-blast ./jobstore 10mammalsplus.txt Anc05.cigar --root Anc05 --pathOverrides panTro6.fa.pp equCab3.fa.pp hg38.fa.pp canFam3.fa.pp felCat8.fa.pp --pathOverrideNames Chimp Horse Human Dog Cat --realTimeLogging --logInfo --retryCount 0 --maxCores 64  --cleanWorkDir never --configFile ./config.xml`

**Comment by gsneha26** [comment]
The error has been fixed in the latest commit.
