### ISSUE TITLE
SegAlign/progressivecactus errors on LSF

### ISSUE THREAD

**Issue by fabrimafe** [gsneha26/SegAlign#48]
Hi,
I am having issues running cactus on LSF, and it seems like a SeqAlign problem. 
I was pointed here from: 
https://github.com/ComparativeGenomicsToolkit/cactus/issues/489
Any ideas?
Thanks!

**Comment by gsneha26** [comment]
1. What is the configuration of the system (GPU, #CPU, etc) being used.
2. Could you share the input files for which it fails?
