### ISSUE TITLE
run_segalign_repeat_masker file

### ISSUE THREAD

**Issue by estolle** [gsneha26/SegAlign#49]
Hi there

I was wondering if the run_segalign_repeat_masker file is missing? I do not see it in the /scripts folder and adapting from the run_seqalign script doesnt yet work for me (runs but no alignment is produced. Is the code to run thetest correct for this?

thanks alot

**Comment by estolle** [comment]
never mind, in another issue I saw a comment that there is no such wrapper script. running it directly worked. 

Perhaps the readme should be corrected (it says there "run_seqalign_repeat_masker")

**Comment by gsneha26** [comment]
I added the file again but your approach of running it directly works too (without resulting in a collated file though).
