### ISSUE TITLE
stdbuf: failed to run command ‘segalign’: No such file or directory

### ISSUE THREAD

**Issue by mdsufz** [gsneha26/SegAlign#51]
Hi. I am trying to test the tool but when I run the last command:

run_segalign ce11.fa cb4.fa --output=ce11.cb4.maf

I get the following error:
stdbuf: failed to run command ‘segalign’: No such file or directory

I don't really understand what is the problem.

**Comment by gsneha26** [comment]
Can you try running 
```
run_seaglign --help

```

to check if the tool is installed correctly.

**Comment by osyafinkelberg** [comment]
Dear Sneha,

I have the same problem. Moreover, when I am running 
```bash
run_segalign --help
```

I receive the same error:
/usr/local/bin/run_segalign: line 60: segalign: command not found
