### ISSUE TITLE
SegAlign Dumps Core on Large Complex Genomes (>8Gb)

### ISSUE THREAD

**Issue by DevonJBoland** [gsneha26/SegAlign#67]
Hello,

I ran across SegAlign after talking with a collaborator who has had previous success using SegAlign to produce alignments in mammilian genomes for downstream comparative analyses. I am trying to perform alignment across several  pairs of locust genomes, that are about twice the size of the human genome ranging from (6-8 Gigbases). Ultimately we want to use these alignments to perform ortholog liftover, but I keep running into an odd error, that I cannot seem to resolve with the help of our HPRC support staff/team.

Our HPC utilized the SLURM job scheduler, and I am currently running SegAlign through a singularity container, built from the docker container make by gsneha26. Originally, the docker container has a hard file limit size. Our HPRC staff rebuilt the continer increasing that file limit from 6Gb to 12Gb to acoomodate our large genomes but I still get the same error:

```
Converting fasta files to 2bit format

Executing: "segalign /scratch/group/songlab/Locust_Genomes/GCF_021461385.2_iqSchPice1.1_genomic.fa /scratch/group/songlab/Locust_Genomes/GCF_023897955.1_iqSchGreg1.2_genomic.fa /scratch/group/songlab/Locust_Genomes/output_15148/data_21109/  --strand both --format maf+ --output iqSchPice.iqSchGreg.maf --num_gpu -1 --debug"
Target /scratch/group/songlab/Locust_Genomes/GCF_021461385.2_iqSchPice1.1_genomic.fa
Query /scratch/group/songlab/Locust_Genomes/GCF_023897955.1_iqSchGreg1.2_genomic.fa
ambiguous
Seed TTT0T00TT00T0T0TTTT
Seed size 19
Transition 1
xdrop 910
HSP threshold 3000
Gapped 1
ydrop 9430
gapped threshold 3000
91 -114 -31 -123 -1000 -1000 -100 -9100
-114 100 -125 -31 -1000 -1000 -100 -9100
-31 -125 100 -114 -1000 -1000 -100 -9100
-123 -31 -114 91 -1000 -1000 -100 -9100
-1000 -1000 -1000 -1000 -1000 -1000 -1000 -9100
-1000 -1000 -1000 -1000 -1000 -1000 -1000 -9100
-100 -100 -100 -100 -1000 -1000 -100 -9100
-9100 -9100 -9100 -9100 -9100 -9100 -9100 -9100
Using 48 threads
Using 2 GPU(s)

Reading query file ...
Not enough memory in query DRAM. Need to reduce input query sequence size to less than 6GB!
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorCudartUnloading: driver shutting down
/usr/local/bin/run_segalign: line 197: 153729 Aborted                 (core dumped) stdbuf -oL segalign $refPath $queryPath $DATA_FOLDER $optionalArguments

real	4m12.239s
user	0m0.000s
sys	0m28.178s

real	4m12.252s
user	1m3.191s
sys	0m39.192s
```

My execution of SegAlign is as follows:

```shell
singularity exec --nv ${sif_path} run_segalign \
	${ref_gen} \
	${query_gen} \
	--strand ${stranded} \
	--format ${format_out} \
	--output ${out_name}.maf \
	--num_gpu -1 \
	--debug
``` 

HPC rescources utilized on the compute node are:

- 2 NVIDIA A100 GPUs
- 48 cores on GPU Node
- 440 Gb Unified RAM (80Gb/GPU + 360Gb from CPU node)

My main question would be what is the suggested workflow to process these large genomes, in your use case/experience? For context, my previous whole genome alignment experience was using Cactus (which I know uses SegAlign) to perform whole genome alignments across ~200Mb green microaglae genomes.

Thank you for the consideration and advice in advance, and please let me know if you need/want any additional information!
-Devon

**Comment by glennhickey** [comment]
Suggestion: try [KegAlign](https://github.com/galaxyproject/KegAlign) and if you run into issues, post on their github instead.

**Comment by DevonJBoland** [comment]
@glennhickey, thanks for the advice. I'll mark this as closed and inform our collaborators to move to KegAlign as well.
